server:
  port: 8088

logging:
  level:
    org.springframework.web: debug
    root: info

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/

spring:
  application:
    name: microservice-consumer-movie

